service: ystavat-loppuprojekti-2

provider:
  name: aws
  runtime: python3.6

# you can overwrite defaults here
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
        - dynamodb:BatchGetItem
        - dynamodb:GetItem
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:BatchWriteItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource: "*"

# you can define service wide environment variables here
  environment:
    REGION_NAME: eu-west-1

functions:
  sendEmail:
    handler: handler.sendEmail
    description: This function will send an email
    events:
      - http:
          path: "send-email"
          method: post
          integration: lambda
          cors: true
          response: 
            headers: 
              "Access-Control-Allow_Origin": "'*'"

resources:
  Resources:
    ystavadynamodb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ystava-viestit-2
        AttributeDefinitions:
          - AttributeName: sender
            AttributeType: S
          - AttributeName: content
            AttributeType: S
        KeySchema:
          - AttributeName: sender
            KeyType: HASH  
          - AttributeName: content
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
